import fs from 'fs';
import path from 'path';
import { execSync } from 'child_process';
import { scanDiffForSecretsAndPII } from './scanner';

// ─── Data Types ─────────────────────────────────────────────────────────────

export interface AICommitRecord {
  sha: string;
  message: string;
  timestamp: string;
  isAi: boolean;
  diffStats: { files: number; additions: number; deletions: number };
  scanResult: {
    passed: boolean;
    violations: string[];
  };
  branchAction: {
    action: 'passed' | 'quarantined' | 'skipped';
    branch?: string;
    reason?: string;
  };
}

export interface AIWatcherData {
  totalCommits: number;
  aiCommits: number;
  humanCommits: number;
  acceptanceRate: number;
  quarantineRate: number;
  records: AICommitRecord[];
}

// ─── Persistence ────────────────────────────────────────────────────────────

function getDataDir(): string {
  const dir = path.join(process.cwd(), '.soloknuckle');
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  return dir;
}

function getWatcherFile(): string {
  return path.join(getDataDir(), 'ai-watcher.json');
}

export function loadWatcherData(): AIWatcherData {
  const file = getWatcherFile();
  if (fs.existsSync(file)) {
    try {
      return JSON.parse(fs.readFileSync(file, 'utf-8'));
    } catch {
      // corrupted, reset
    }
  }
  return {
    totalCommits: 0,
    aiCommits: 0,
    humanCommits: 0,
    acceptanceRate: 0,
    quarantineRate: 0,
    records: [],
  };
}

export function saveWatcherData(data: AIWatcherData): void {
  fs.writeFileSync(getWatcherFile(), JSON.stringify(data, null, 2));
}

// ─── Detection ──────────────────────────────────────────────────────────────

const AI_SIGNATURES = [
  /co-authored-by:.*copilot/i,
  /co-authored-by:.*claude/i,
  /co-authored-by:.*gpt/i,
  /co-authored-by:.*ai/i,
  /generated by.*ai/i,
  /ai-generated/i,
  /automated.*commit/i,
  /cursor/i,
  /windsurf/i,
  /replit.*agent/i,
  /anthropic/i,
  /openai/i,
];

export function isAICommit(message: string): boolean {
  return AI_SIGNATURES.some(pattern => pattern.test(message));
}

// ─── Core Logic ─────────────────────────────────────────────────────────────

export interface WatchResult {
  record: AICommitRecord;
  success: boolean;
  message: string;
}

/**
 * Watches a specific commit: determines if it's AI, scans the diff,
 * and either passes it (feature branch) or quarantines it (revert branch).
 */
export function watchCommit(sha?: string): WatchResult {
  const data = loadWatcherData();

  // Get commit info
  let commitSha: string;
  let commitMessage: string;

  if (sha) {
    commitSha = sha;
    try {
      commitMessage = execSync(`git log -1 --format=%s ${sha}`, { encoding: 'utf-8', cwd: process.cwd() }).trim();
    } catch {
      return { record: null as unknown as AICommitRecord, success: false, message: `Could not read commit ${sha}` };
    }
  } else {
    // Use HEAD
    try {
      commitSha = execSync('git rev-parse HEAD', { encoding: 'utf-8', cwd: process.cwd() }).trim();
      commitMessage = execSync('git log -1 --format=%s', { encoding: 'utf-8', cwd: process.cwd() }).trim();
    } catch {
      return { record: null as unknown as AICommitRecord, success: false, message: 'Not a git repository or no commits.' };
    }
  }

  // Check if already watched
  if (data.records.some(r => r.sha === commitSha)) {
    return { record: data.records.find(r => r.sha === commitSha)!, success: true, message: 'Commit already watched.' };
  }

  const isAi = isAICommit(commitMessage);

  // Get diff for this commit
  let diff = '';
  let diffStats = { files: 0, additions: 0, deletions: 0 };
  try {
    diff = execSync(`git diff ${commitSha}~1..${commitSha}`, { encoding: 'utf-8', cwd: process.cwd(), stdio: 'pipe' });
    const statOutput = execSync(`git diff --numstat ${commitSha}~1..${commitSha}`, { encoding: 'utf-8', cwd: process.cwd(), stdio: 'pipe' });
    const lines = statOutput.trim().split('\n').filter(Boolean);
    diffStats.files = lines.length;
    for (const line of lines) {
      const parts = line.split('\t');
      if (parts[0] !== '-') diffStats.additions += parseInt(parts[0]) || 0;
      if (parts[1] !== '-') diffStats.deletions += parseInt(parts[1]) || 0;
    }
  } catch {
    // Could be first commit
  }

  // Scan for secrets/PII
  const violations = scanDiffForSecretsAndPII(diff);
  const passed = violations.length === 0;

  let branchAction: AICommitRecord['branchAction'] = { action: 'skipped' };

  if (isAi) {
    if (passed) {
      // Create feature branch for AI commit that passes
      const branchName = `ai-approved/${commitSha.substring(0, 8)}`;
      try {
        execSync(`git branch ${branchName} ${commitSha}`, { cwd: process.cwd(), stdio: 'pipe' });
        branchAction = { action: 'passed', branch: branchName, reason: 'AI commit passed security scan.' };
      } catch {
        branchAction = { action: 'passed', branch: branchName, reason: 'Branch creation failed (branch may already exist).' };
      }
    } else {
      // Quarantine: create quarantine branch
      const quarantineBranch = `quarantine/${commitSha.substring(0, 8)}`;
      try {
        execSync(`git branch ${quarantineBranch} ${commitSha}`, { cwd: process.cwd(), stdio: 'pipe' });
        branchAction = { action: 'quarantined', branch: quarantineBranch, reason: `AI commit failed security scan: ${violations.length} violation(s).` };
      } catch {
        branchAction = { action: 'quarantined', branch: quarantineBranch, reason: `AI commit failed security scan. Branch creation failed.` };
      }
    }
  }

  const record: AICommitRecord = {
    sha: commitSha,
    message: commitMessage,
    timestamp: new Date().toISOString(),
    isAi,
    diffStats,
    scanResult: { passed, violations },
    branchAction,
  };

  data.records.push(record);
  data.totalCommits++;

  if (isAi) {
    data.aiCommits++;
  } else {
    data.humanCommits++;
  }

  // Recalculate rates
  const aiRecords = data.records.filter(r => r.isAi);
  const accepted = aiRecords.filter(r => r.branchAction.action === 'passed').length;
  const quarantined = aiRecords.filter(r => r.branchAction.action === 'quarantined').length;
  data.acceptanceRate = aiRecords.length > 0 ? Math.round((accepted / aiRecords.length) * 100) : 0;
  data.quarantineRate = aiRecords.length > 0 ? Math.round((quarantined / aiRecords.length) * 100) : 0;

  saveWatcherData(data);

  return {
    record,
    success: true,
    message: isAi
      ? passed
        ? `AI commit approved → branch '${branchAction.branch}'`
        : `AI commit quarantined → branch '${branchAction.branch}' (${violations.length} violations)`
      : 'Human commit logged (no action taken).',
  };
}

/**
 * Watches the last N commits (default: 10).
 */
export function watchRecentCommits(count: number = 10): WatchResult[] {
  const results: WatchResult[] = [];
  try {
    const shas = execSync(`git log --oneline -${count} --format=%H`, { encoding: 'utf-8', cwd: process.cwd() })
      .trim().split('\n').filter(Boolean);
    for (const sha of shas) {
      results.push(watchCommit(sha));
    }
  } catch {
    // not a git repo
  }
  return results;
}

/**
 * Returns a summary of the watcher data.
 */
export function getWatcherSummary(): string {
  const data = loadWatcherData();
  return [
    `Total commits tracked: ${data.totalCommits}`,
    `AI commits: ${data.aiCommits}`,
    `Human commits: ${data.humanCommits}`,
    `AI acceptance rate: ${data.acceptanceRate}%`,
    `AI quarantine rate: ${data.quarantineRate}%`,
    `Records: ${data.records.length}`,
  ].join('\n');
}
