import chalk from 'chalk';
import crypto from 'crypto';
import fs from 'fs';
import path from 'path';
import { execSync } from 'child_process';
import express from 'express';
import cors from 'cors';

// ─── Incident History ───────────────────────────────────────────────────────

export interface IncidentRecord {
  id: string;
  timestamp: string;
  source: string;
  title: string;
  severity: string;
  culprit?: string;
  aiRelated: boolean;
  revertedCommit?: string;
  revertBranch?: string;
  prCreated: boolean;
  notified: boolean;
}

function getDataDir(): string {
  const dir = path.join(process.cwd(), '.soloknuckle');
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  return dir;
}

function getIncidentsFile(): string {
  return path.join(getDataDir(), 'incidents.json');
}

function loadIncidents(): IncidentRecord[] {
  const file = getIncidentsFile();
  if (fs.existsSync(file)) {
    try { return JSON.parse(fs.readFileSync(file, 'utf-8')); } catch { return []; }
  }
  return [];
}

function saveIncidents(records: IncidentRecord[]): void {
  fs.writeFileSync(getIncidentsFile(), JSON.stringify(records, null, 2));
}

// ─── Sentry Payload Parsing ─────────────────────────────────────────────────

export interface SentryIncident {
  id: string;
  title: string;
  culprit?: string;
  level: string;
  project?: string;
  url?: string;
  timestamp: string;
}

/**
 * Parses a Sentry webhook payload (issue or metric alert).
 * Supports both Sentry Issue Webhooks and Metric Alert Webhooks.
 */
export function parseSentryPayload(body: Record<string, unknown>): SentryIncident | null {
  // Sentry Issue Webhook (issue.created, issue.assigned, etc.)
  if (body.data && typeof body.data === 'object') {
    const data = body.data as Record<string, unknown>;
    if (data.issue) {
      const issue = data.issue as Record<string, unknown>;
      return {
        id: String(issue.id || ''),
        title: String(issue.title || 'Unknown Issue'),
        culprit: issue.metadata ? String((issue.metadata as Record<string, unknown>).function || '') : undefined,
        level: String(issue.level || 'error'),
        project: issue.project ? String((issue.project as Record<string, unknown>).slug || '') : undefined,
        url: String(issue.permalink || ''),
        timestamp: String(issue.timestamp || new Date().toISOString()),
      };
    }
  }

  // Metric Alert Webhook (triggers on metric threshold)
  if (body.event && typeof body.event === 'object') {
    const event = body.event as Record<string, unknown>;
    const data = event.data as Record<string, unknown> | undefined;
    return {
      id: String(body.event?.id || Date.now()),
      title: String(data?.title || body.event?.title || 'Metric Alert Triggered'),
      culprit: data?.culprit ? String(data.culprit) : undefined,
      level: 'error',
      project: data?.project_slug ? String(data.project_slug) : undefined,
      url: body.data?.web_url ? String(body.data.web_url) : undefined,
      timestamp: new Date().toISOString(),
    };
  }

  // Fallback: minimal incident from any webhook body
  if (body.title || body.message) {
    return {
      id: String(body.id || Date.now()),
      title: String(body.title || body.message),
      culprit: body.culprit ? String(body.culprit) : undefined,
      level: String(body.level || body.severity || 'error'),
      timestamp: new Date().toISOString(),
    };
  }

  return null;
}

// ─── AI Commit Detection for Rollback ──────────────────────────────────────

const AI_COMMIT_PATTERNS = [
  /co-authored-by:.*copilot/i,
  /co-authored-by:.*claude/i,
  /co-authored-by:.*gpt/i,
  /co-authored-by:.*ai/i,
  /generated by.*ai/i,
  /ai-generated/i,
  /cursor/i,
  /windsurf/i,
  /anthropic/i,
  /openai/i,
];

function isAICommit(message: string): boolean {
  return AI_COMMIT_PATTERNS.some(p => p.test(message));
}

/**
 * Finds the most recent AI-authored commit that could be a culprit.
 * Returns { sha, message } or null.
 */
function findRecentAICommit(since?: string): { sha: string; message: string } | null {
  try {
    const sinceFlag = since ? `--since="${since}"` : '-20';
    const log = execSync(`git log ${sinceFlag} --format=%H|||%s`, { encoding: 'utf-8', cwd: process.cwd(), stdio: 'pipe' });
    const lines = log.trim().split('\n').filter(Boolean);
    for (const line of lines) {
      const [sha, ...msgParts] = line.split('|||');
      const message = msgParts.join('|||');
      if (isAICommit(message)) {
        return { sha, message };
      }
    }
  } catch {
    // not a git repo
  }
  return null;
}

/**
 * Reverts a specific commit and creates a branch for review.
 */
export function revertCommit(sha: string): { success: boolean; revertSha?: string; branch?: string; error?: string } {
  const revertBranch = `revert/${sha.substring(0, 8)}-${Date.now()}`;

  try {
    // Create branch from current HEAD before reverting
    execSync(`git branch ${revertBranch}`, { cwd: process.cwd(), stdio: 'pipe' });

    // Create revert commit
    const revertOutput = execSync(`git revert ${sha} --no-edit`, { encoding: 'utf-8', cwd: process.cwd(), stdio: 'pipe' });
    const revertSha = execSync('git rev-parse HEAD', { encoding: 'utf-8', cwd: process.cwd() }).trim();

    return { success: true, revertSha, branch: revertBranch };
  } catch (e: unknown) {
    // If revert fails (merge conflicts), reset and report
    try { execSync('git revert --abort', { stdio: 'ignore', cwd: process.cwd() }); } catch { /* ignore */ }
    return {
      success: false,
      error: e instanceof Error ? e.message : 'Revert failed (possible merge conflict).',
      branch: revertBranch,
    };
  }
}

/**
 * Creates a PR-like report for the rollback (as a markdown file since we don't have GitHub API access).
 */
function createRollbackReport(incident: SentryIncident, aiCommit: { sha: string; message: string }, revertSha: string, revertBranch: string): string {
  const reportPath = path.join(getDataDir(), `rollback-report-${Date.now()}.md`);
  const report = `# Auto-Rollback Report

## Incident
- **Title:** ${incident.title}
- **Severity:** ${incident.level}
- **Source:** ${incident.url || 'N/A'}
- **Detected at:** ${new Date().toISOString()}

## Culprit Commit (AI-Authored)
- **SHA:** ${aiCommit.sha}
- **Message:** ${aiCommit.message}
- **Reverted to:** ${revertSha}

## Action Taken
- Reverted commit \`${aiCommit.sha.substring(0, 8)}\`
- Created branch: \`${revertBranch}\`
- Review the branch and merge when ready

## Next Steps
1. Review the revert branch: \`git log ${revertBranch}\`
2. Test the reverted state locally
3. Merge to main when confident
4. Investigate root cause and re-apply fix properly
`;
  fs.writeFileSync(reportPath, report);
  return reportPath;
}

// ─── Webhook Server ─────────────────────────────────────────────────────────

function verifyWebhookSecret(req: express.Request): boolean {
  const secret = process.env.WEBHOOK_SECRET;
  if (!secret) {
    if (!(global as Record<string, unknown>).__webhookSecretWarned) {
      console.log(chalk.yellow('⚠️  WARNING: No WEBHOOK_SECRET configured. Webhook requests will be accepted without verification.'));
      console.log(chalk.dim('   Set WEBHOOK_SECRET environment variable for production use.'));
      (global as Record<string, unknown>).__webhookSecretWarned = true;
    }
    return true;
  }
  const signature = req.headers['x-webhook-secret'] || req.headers['x-hub-signature-256'];
  if (!signature) return false;
  const sigBuf = Buffer.from(String(signature));
  const secretBuf = Buffer.from(secret);
  if (sigBuf.length !== secretBuf.length) return false;
  return crypto.timingSafeEqual(sigBuf, secretBuf);
}

export function initWebhookListener() {
  const PORT = process.env.WEBHOOK_PORT || 3002;
  const app = express();

  app.use(cors());
  app.use(express.json());

  console.log(chalk.yellow(`Starting Rollback Daemon on port ${PORT}...`));

  // ─── Existing: Feature Flag Rollback ───────────────────────────────────
  app.post('/webhooks/rollback', (req, res) => {
    if (!verifyWebhookSecret(req)) {
      console.log(chalk.red('[SECURITY] Webhook rejected: invalid or missing secret'));
      return res.status(401).json({ error: 'Unauthorized: missing or invalid webhook secret' });
    }

    const { flagName, reason } = req.body;

    if (!flagName || typeof flagName !== 'string') {
      return res.status(400).json({ error: 'Missing or invalid flagName in webhook payload' });
    }

    if (flagName.includes('..') || flagName.includes('/') || flagName.includes('\\')) {
      return res.status(400).json({ error: 'Invalid flagName: path characters not allowed' });
    }

    console.log(chalk.red(`\n[CRITICAL ALERT RECEIVED] Reason: ${reason || 'Automated Error Threshold Triggered'}`));
    console.log(chalk.yellow(`Attempting to rollback feature flag: '${flagName}'...`));

    const flagsPath = path.join(process.cwd(), 'flags.json');

    if (!fs.existsSync(flagsPath)) {
      console.log(chalk.red(`Rollback failed: 'flags.json' not found in project root.`));
      return res.status(404).json({ error: 'flags.json not found' });
    }

    try {
      const flagsData = fs.readFileSync(flagsPath, 'utf-8');
      const flags = JSON.parse(flagsData);

      if (flags[flagName] === undefined) {
        console.log(chalk.yellow(`Flag '${flagName}' does not exist in flags.json.`));
        return res.status(400).json({ error: `Flag '${flagName}' not found` });
      }

      flags[flagName] = false;
      fs.writeFileSync(flagsPath, JSON.stringify(flags, null, 2));

      console.log(chalk.green(`Rollback successful. Feature '${flagName}' is now DISABLED.`));
      res.json({ success: true, message: `Flag '${flagName}' disabled` });

    } catch (err: unknown) {
      const message = err instanceof Error ? err.message : 'Unknown error';
      console.log(chalk.red(`Error processing rollback: ${message}`));
      res.status(500).json({ error: 'Failed to process flags.json' });
    }
  });

  // ─── New: Sentry Incident Auto-Rollback ────────────────────────────────
  app.post('/webhooks/sentry', (req, res) => {
    if (!verifyWebhookSecret(req)) {
      console.log(chalk.red('[SECURITY] Sentry webhook rejected: invalid or missing secret'));
      return res.status(401).json({ error: 'Unauthorized' });
    }

    const incident = parseSentryPayload(req.body);
    if (!incident) {
      return res.status(400).json({ error: 'Could not parse Sentry payload' });
    }

    console.log(chalk.red(`\n[SENTRY INCIDENT] ${incident.title} (${incident.level})`));

    const incidents = loadIncidents();
    const record: IncidentRecord = {
      id: incident.id,
      timestamp: new Date().toISOString(),
      source: 'sentry',
      title: incident.title,
      severity: incident.level,
      culprit: incident.culprit,
      aiRelated: false,
      prCreated: false,
      notified: false,
    };

    // Check if an AI commit is the likely culprit
    const aiCommit = findRecentAICommit();
    if (aiCommit) {
      record.aiRelated = true;
      record.culprit = aiCommit.sha;
      console.log(chalk.yellow(`AI-authored commit detected: ${aiCommit.sha.substring(0, 8)} — ${aiCommit.message}`));

      // Attempt revert
      const revert = revertCommit(aiCommit.sha);
      if (revert.success) {
        record.revertedCommit = revert.revertSha;
        record.revertBranch = revert.branch;

        // Create rollback report
        const reportPath = createRollbackReport(incident, aiCommit, revert.revertSha!, revert.branch!);
        record.prCreated = true;

        console.log(chalk.green(`Auto-reverted commit ${aiCommit.sha.substring(0, 8)}.`));
        console.log(chalk.green(`Revert branch: ${revert.branch}`));
        console.log(chalk.green(`Report: ${reportPath}`));
      } else {
        console.log(chalk.red(`Revert failed: ${revert.error}`));
        console.log(chalk.yellow('Manual intervention required.'));
      }
    } else {
      console.log(chalk.yellow('No AI-authored commits found as potential culprit.'));
      console.log(chalk.yellow('Manual investigation required.'));
    }

    // Notify via console (extensible to Slack/email)
    record.notified = true;
    console.log(chalk.cyan(`[NOTIFY] Incident ${incident.id} processed. AI-related: ${record.aiRelated}`));

    incidents.push(record);
    saveIncidents(incidents);

    res.json({
      success: true,
      incident: {
        id: incident.id,
        title: incident.title,
        aiRelated: record.aiRelated,
        reverted: !!record.revertedCommit,
        revertBranch: record.revertBranch,
        reportCreated: record.prCreated,
      },
    });
  });

  // ─── New: Incident History ─────────────────────────────────────────────
  app.get('/webhooks/incidents', (_req, res) => {
    res.json(loadIncidents());
  });

  app.listen(PORT, () => {
    console.log(chalk.green(`Listening for webhooks at http://localhost:${PORT}/webhooks/rollback`));
    console.log(chalk.green(`Sentry incident endpoint at http://localhost:${PORT}/webhooks/sentry`));
    console.log(chalk.green(`Incident history at http://localhost:${PORT}/webhooks/incidents`));
  });
}
